baseurl = "https://imageresizer.online/blog/"
languageCode = "en-us"
title = "Image Resizer Online Blog"
theme = "hugo-steam-theme"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-98784571-1"
# Number of posts per page
paginate = 10

[params]
	title = "Image Resizer Online Blog"
	subtitle = "A simple fast online image resizer"
	description = ""

	# You can choose between green, orange, red and blue.
	themecolor = "blue"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"


#baseURL = "https://imageresizer.online/blog/"
#languageCode = "en-us"
#title = "Image Resizer Online Blog"
#theme = "hyde"